### ISSUE TITLE
Content negotiation on W3C spec

### ISSUE THREAD

**Issue by SvenLieber** [pietercolpaert/ldfetch#22]
When fetching *a* RDF representation of an ontology from its URI, the *text/html* content-type gets chosen in the case of a spec page (although a turtle and json-ld variant exist).
This however, leads to the error: `TypeError: Cannot read property 'length' of undefined`.

Reproducible with the command `ldfetch http://www.w3.org/ns/csvw#`

As workaround for such a case, ldfetch can be initialized with a custom *Accept* header not using *text/html*.

**Comment by pietercolpaert** [comment]
Tackled in #24
