### ISSUE TITLE
Dive into datatype rdf:HTML

### ISSUE THREAD

**Issue by csarven** [pietercolpaert/ldfetch#25]
eg `ldfetch https://linkedresearch.org/cloud` returns:

`<https://linkedresearch.org/cloud#faq> <http://schema.org/description> "[object NodeList]"^^<http://www.w3.org/1999/02/22-rdf-syntax-ns#HTML>.`

**Comment by pietercolpaert** [comment]
Interesting bug! The problem resides in the RDFa-processor’s way of handling HTML elements. See https://github.com/pietercolpaert/rdfa-processor/blob/master/src/RDFaProcessor.js#L839-L842

Instead of returning the DOM elements there, we should convert this to a string.

**Comment by pietercolpaert** [comment]
Fixed in latest commit!
